name: Auto Commit

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate random commits
        run: |

          DAY=$(date +%u)

          if [ $DAY -ge 6 ]; then
            commits=$((RANDOM % 6 + 3))
          else
            commits=$((RANDOM % 5 + 1))
          fi

          git config user.name "Co0lboy"
          git config user.email "pawarani002@gmail.com"

          for i in $(seq 1 $commits)
          do
            echo "update $(date '+%Y-%m-%d %H:%M:%S') $RANDOM" >> log.txt

            git add log.txt
            git commit -m "update $i"

            sleep $((RANDOM % 15 + 5))
          done

          git pull origin main --rebase || true
          git push
